countries=[
	'AfriqueduSud','Algerie','Angola','Benin','Botswana',
	'Burkina','Burundi','Cameroun','CapVert','Republiquecentrafricaine',
	'Comores','Congo','RepubliquedemocratiqueduCongo',"CotedIvoire",'Djibouti',
	'egypte','erythree','ethiopie','Gabon','Gambie',
	'Ghana','Guinee','GuineeBissau','Guineeequatoriale','Kenya',
	'Lesotho','Liberia','Libye','Madagascar','Malawi',
	'Mali','Maroc','Maurice','Mauritanie','Mozambique',
	'Namibie','Niger','Nigeria','Ouganda','Rwanda',
	'SaoTomeetPrincipe','Senegal','Seychelles','SierraLeone','Somalie',
	'Soudan','SudSoudan','Swaziland','Tanzanie','Tchad',
	'Togo','Tunisie','Zambie','Zimbabwe','iguaetBarbuda',
	'Argentine','Bahamas','Barbade','Belize','Bolivie',
	'Bresil','Canada','Chili','Colombie','CostaRica',
	'Cuba','Republiquedominicaine','Dominique','equateur','etatsUnis',
	'Grenade','Guatemala','Guyana','Haiti','Honduras',
	'Jamaique','Mexique','Nicaragua','Panama','Paraguay',
	'Perou','PortoRico','SaintChristopheetNieves','SainteLucie','SaintVincentetlesGrenadines',
	'Salvador','Suriname','TriniteetTobago','Uruguay','Venezuela',
	'Afghanistan','Arabiesaoudite','Bahrein','Bangladesh','Bhoutan',
	'Birmanie','Brunei','Cambodge','Chine','CoreeduNord',
	'CoreeduSud','emiratsarabesunis','Inde','Indonesie','Irak',
	'Iran','Israel','Japon','Jordanie','Kazakhstan',
	'Kirghizistan','Koweit','Laos','Liban','Malaisie',
	'Maldives','Mongolie','Nepal','Oman','Ouzbekistan',
	'Palestine','Pakistan','Philippines','Qatar','Singapour',
	'SriLanka','Syrie','Tadjikistan','Taiwan','Thailande',
	'Timororiental','Turkmenistan','Turquie','VietNam','Yemen',
	'Allemagne','Albanie','Andorre','Armenie','Autriche',
	'Azerbaidjan','Belgique','Bielorussie','BosnieHerzegovine','Bulgarie',
	'Chypre','Croatie','Danemark','Espagne','Estonie',
	'Finlande','France','Georgie','Grece','Hongrie',
	'Irlande','Islande','Italie','Lettonie','Liechtenstein',
	'Lituanie','Luxembourg','RepubliquedeMacedoine','Malte','Moldavie',
	'Monaco','Montenegro','Norvege','PaysBas','Pologne',
	'Portugal','Republiquetcheque','Roumanie','RoyaumeUni','Russie',
	'SaintMarin','Serbie','Slovaquie','Slovenie','Suede',
	'Suisse','Ukraine','Vatican','Australie','Fidji',
	'Kiribati','Marshall','Micronesie','Nauru','NouvelleZelande',
	'Palaos','PapouasieNouvelleGuinee','Salomon','Samoa','Tonga',
	'Tuvalu','Vanuatu']


cities = ['Aerschot', 'Alost', 'Andenne', 'Antoing', 'Anvers', 'Arlon', 'Ath', 'Aubange', 'Audenarde', 
		'Bastogne', 'Beaumont', 'Beauraing', 'Beringen', 'Bilzen', 'Binche', 'Blankenberghe', 'Bouillon', 
		'BraineleComte', 'Bree', 'Bruges', 'Bruxelles', 'Charleroi', 'Chatelet', 'Chievres', 'Chimay', 'Chiny', 
		'Ciney', 'CominesWarneton', 'Courtrai', 'Couvin', 'Damme', 'Deinze', 'Diest', 'DilsenStokkem', 'Dinant', 
		'Dixmude', 'Durbuy', 'Eeklo', 'Enghien', 'Eupen', 'Fleurus', 'Florenville', 'FontainelEveque', 'FosseslaVille', 
		'Furnes', 'Gand', 'Geel', 'Gembloux', 'Genappe', 'Genk', 'Gistel', 'Grammont', 'Hal', 'Halen', 'HamontAchel', 
		'Hannut', 'Harelbeke', 'Hasselt', 'HercklaVille', 'Herentals', 'Herstal', 'Herve', 'Hoogstraten', 'Houffalize', 
		'Huy', 'Izegem', 'Jodoigne', 'Landen', 'Leau', 'Le', 'Lessines', 'LeuzeenHainaut', 'Liege', 'Lierre', 'Limbourg', 
		'Lokeren', 'Lommel', 'Looz', 'LoReninge', 'Louvain', 'Maaseik', 'Malines', 'Malmedy', 'MarcheenFamenne', 'Menin', 
		'Messines', 'Mons', 'MontaiguZichem', 'Mortsel', 'Mouscron', 'Namur', 'Neufchateau', 'Nieuport', 'Ninove', 'Nivelles', 
		'Ostende', 'OttigniesLouvainlaNeuve', 'Oudenburg', 'Peer', 'Philippeville', 'Poperinge', 'Renaix', 'Rochefort', 
		'Roulers', 'SaintGhislain', 'SaintHubert', 'SaintNicolas', 'SaintTrond', 'SaintVith', 'Seraing', 'Soignies', 
		'Spa', 'Stavelot', 'Termonde', 'Thourout', 'Thuin', 'Tielt', 'Tirlemont', 'Tongres', 'Tournai', 'Tubize', 
		'Turnhout', 'Verviers', 'Vilvorde', 'Virton', 'Vise', 'Walcourt', 'Waregem', 'Waremme', 'Wavre', 'Wervicq', 'Ypres']